### ISSUE TITLE
base64: invalid option -- w

### ISSUE THREAD

**Issue by keithdtyler** [elsamuko/urlzip#1]

**Comment by elsamuko** [comment]
On a mac? Should work with GNU base64.

**Comment by keithdtyler** [comment]
Yeah, sometimes that's installed as gbase64 depending on how you install the brew (and if you use anything else that expects non-gnu tools).

The BSD form of the `-w` argument is `-b` btw.

**Comment by elsamuko** [comment]
This is ok as fix?
